linkedin:
  client:
      clientId: 78xdqcj1hualk0
      clientSecret: 9COf1uy0Oadxikqe
      userAuthorizationUri: https://www.linkedin.com/oauth/v2/authorization
      accessTokenUri: https://www.linkedin.com/oauth/v2/accessToken
      scope:
      tokenName: access_token
      authenticationScheme: header
      clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.linkedin.com/v1/people/~:(first-name,last-name,headline,summary,email-address)?format=json